"""
Agent Protocols
===============
에이전트에 대한 추상 인터페이스
"""

from typing import Protocol, List, Dict, Any, Optional, runtime_checkable


@runtime_checkable
class CrawlerAgentProtocol(Protocol):
    """크롤러 에이전트 Protocol"""
    async def crawl(self, categories: List[str]) -> List[Any]: ...
    async def crawl_single(self, category_id: str, url: str) -> List[Any]: ...
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...


@runtime_checkable
class StorageAgentProtocol(Protocol):
    """저장소 에이전트 Protocol"""
    async def save(self, records: List[Any]) -> bool: ...
    async def save_metrics(self, metrics: Dict[str, Any]) -> bool: ...
    async def initialize(self) -> None: ...


@runtime_checkable
class MetricsAgentProtocol(Protocol):
    """메트릭 계산 에이전트 Protocol"""
    async def calculate(self, records: List[Any]) -> Dict[str, Any]: ...
    async def calculate_brand_metrics(self, records: List[Any], brand: str, category_id: str) -> Any: ...
    async def calculate_market_metrics(self, records: List[Any], category_id: str) -> Any: ...


@runtime_checkable
class InsightAgentProtocol(Protocol):
    """인사이트 생성 에이전트 Protocol"""
    async def generate(self, metrics: Dict[str, Any], records: Optional[List[Any]] = None) -> List[Dict[str, Any]]: ...
    async def generate_for_brand(self, brand: str, metrics: Dict[str, Any], competitors: Optional[List[str]] = None) -> List[Dict[str, Any]]: ...
    async def generate_alerts(self, metrics: Dict[str, Any], thresholds: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]: ...


@runtime_checkable
class ChatAgentProtocol(Protocol):
    """챗봇 에이전트 Protocol"""
    async def respond(self, query: str, session_id: Optional[str] = None) -> Dict[str, Any]: ...
    async def respond_with_context(self, query: str, context: Dict[str, Any], session_id: Optional[str] = None) -> Dict[str, Any]: ...
