"""Repository Protocol definitions"""

from datetime import date
from typing import Protocol


class ProductRepository(Protocol):
    """Abstract repository for product data persistence"""

    async def save_records(self, records: list) -> bool: ...
    async def get_recent(self, days: int = 7) -> list: ...
    async def get_by_category(self, category_id: str, date: date | None = None) -> list: ...
    async def get_by_brand(self, brand: str, days: int = 7) -> list: ...


class MetricsRepository(Protocol):
    """Abstract repository for metrics persistence"""

    async def save_brand_metrics(self, metrics: list) -> bool: ...
    async def save_market_metrics(self, metrics: list) -> bool: ...
    async def get_brand_metrics(self, brand: str, category_id: str) -> dict | None: ...
    async def get_market_metrics(
        self, category_id: str, date: date | None = None
    ) -> dict | None: ...
