"""Repository Protocol definitions"""
from typing import Protocol, List, Optional
from datetime import date

class ProductRepository(Protocol):
    """Abstract repository for product data persistence"""
    async def save_records(self, records: List) -> bool: ...
    async def get_recent(self, days: int = 7) -> List: ...
    async def get_by_category(self, category_id: str, date: Optional[date] = None) -> List: ...
    async def get_by_brand(self, brand: str, days: int = 7) -> List: ...

class MetricsRepository(Protocol):
    """Abstract repository for metrics persistence"""
    async def save_brand_metrics(self, metrics: List) -> bool: ...
    async def save_market_metrics(self, metrics: List) -> bool: ...
    async def get_brand_metrics(self, brand: str, category_id: str) -> Optional[dict]: ...
    async def get_market_metrics(self, category_id: str, date: Optional[date] = None) -> Optional[dict]: ...
