"""Scraper Protocol definition"""
from typing import Protocol, List

class ScraperProtocol(Protocol):
    """Protocol for web scraper implementations"""
    async def initialize(self) -> None: ...
    async def scrape_category(self, category_id: str, url: str) -> List: ...
    async def scrape_all_categories(self) -> List: ...
    async def close(self) -> None: ...
