"""Scraper Protocol definition"""

from typing import Protocol


class ScraperProtocol(Protocol):
    """Protocol for web scraper implementations"""

    async def initialize(self) -> None: ...
    async def scrape_category(self, category_id: str, url: str) -> list: ...
    async def scrape_all_categories(self) -> list: ...
    async def close(self) -> None: ...
